version: "3"

networks:
  backend:
    driver: bridge

services:
  mysql:
    image: mysql:8.0
    container_name: go_demo_mysql
    command: --default-authentication-plugin=mysql_native_password
    #        working_dir: /application
    volumes:
      - .:/application
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_DATABASE=question
      - MYSQL_USER=mysql_user
      - MYSQL_PASSWORD=mysql_password
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
    ports:
      - "8088:3306"
    networks:
      - backend
  backend:
    container_name: go_demo_backend
    build:
      context: .
    tty: true
    volumes:
      - /home/neolab/working/workingspace/revel-demo/backend/build:/go/src
    working_dir: /go/src
    command: ./main
    ports:
      - 50052:50051
    depends_on:
      - mysql
    networks:
      - backend
volumes:
  mysql:
    driver: local
