version: "3"

networks:
  backend:
    driver: bridge

services:
  mysql:
    image: mysql:8.0
    container_name: go_demo_mysql
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - /home/neolab/working/workingspace/revel-demo/backend/database/data:/var/lib/mysql
      - /home/neolab/working/workingspace/revel-demo/backend/database/migrate:/docker-entrypoint-initdb.d
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=questions
      - MYSQL_USER=mysql_user
      - MYSQL_PASSWORD=mysql_password
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
    ports:
      - "8088:3306"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    networks:
      - backend
  backend:
    container_name: go_demo_backend
    build:
      context: .
    tty: true
    volumes:
      - /home/neolab/working/workingspace/revel-demo/backend/build:/go/src
    working_dir: /go/src
    command: ./main
    restart: on-failure
    ports:
      - 9090:9090
    depends_on:
      - mysql
    networks:
      - backend
  
  front-envoy:
    container_name: go_demo_envoy
    image: envoyproxy/envoy-alpine:v1.14-latest
    volumes:
      - ./front-envoy.yaml:/etc/envoy/envoy.yaml
    networks:
      - backend
    ports:
      - "9901:9901"
      - "50051:50051"
volumes:
  mysql:
    driver: local
