// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        (unknown)
// source: protos/round/message.proto

package round

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type RoundMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id    string  `protobuf:"bytes,1,opt,name=Id,json=id,proto3" json:"Id,omitempty"`
	Name  string  `protobuf:"bytes,2,opt,name=Name,json=name,proto3" json:"Name,omitempty"`
	Score float32 `protobuf:"fixed32,3,opt,name=Score,json=score,proto3" json:"Score,omitempty"`
}

func (x *RoundMessage) Reset() {
	*x = RoundMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_round_message_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoundMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoundMessage) ProtoMessage() {}

func (x *RoundMessage) ProtoReflect() protoreflect.Message {
	mi := &file_protos_round_message_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoundMessage.ProtoReflect.Descriptor instead.
func (*RoundMessage) Descriptor() ([]byte, []int) {
	return file_protos_round_message_proto_rawDescGZIP(), []int{0}
}

func (x *RoundMessage) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RoundMessage) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RoundMessage) GetScore() float32 {
	if x != nil {
		return x.Score
	}
	return 0
}

type ListRoundRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListRoundRequest) Reset() {
	*x = ListRoundRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_round_message_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListRoundRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRoundRequest) ProtoMessage() {}

func (x *ListRoundRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_round_message_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRoundRequest.ProtoReflect.Descriptor instead.
func (*ListRoundRequest) Descriptor() ([]byte, []int) {
	return file_protos_round_message_proto_rawDescGZIP(), []int{1}
}

type ListRoundResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Items []*RoundMessage `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
}

func (x *ListRoundResponse) Reset() {
	*x = ListRoundResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_round_message_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListRoundResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRoundResponse) ProtoMessage() {}

func (x *ListRoundResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_round_message_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRoundResponse.ProtoReflect.Descriptor instead.
func (*ListRoundResponse) Descriptor() ([]byte, []int) {
	return file_protos_round_message_proto_rawDescGZIP(), []int{2}
}

func (x *ListRoundResponse) GetItems() []*RoundMessage {
	if x != nil {
		return x.Items
	}
	return nil
}

type GetRoundRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=Id,json=id,proto3" json:"Id,omitempty"`
}

func (x *GetRoundRequest) Reset() {
	*x = GetRoundRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_round_message_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRoundRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRoundRequest) ProtoMessage() {}

func (x *GetRoundRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_round_message_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRoundRequest.ProtoReflect.Descriptor instead.
func (*GetRoundRequest) Descriptor() ([]byte, []int) {
	return file_protos_round_message_proto_rawDescGZIP(), []int{3}
}

func (x *GetRoundRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetRoundResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Item *RoundMessage `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
}

func (x *GetRoundResponse) Reset() {
	*x = GetRoundResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_round_message_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRoundResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRoundResponse) ProtoMessage() {}

func (x *GetRoundResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_round_message_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRoundResponse.ProtoReflect.Descriptor instead.
func (*GetRoundResponse) Descriptor() ([]byte, []int) {
	return file_protos_round_message_proto_rawDescGZIP(), []int{4}
}

func (x *GetRoundResponse) GetItem() *RoundMessage {
	if x != nil {
		return x.Item
	}
	return nil
}

type CreateRoundRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Item *RoundMessage `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
}

func (x *CreateRoundRequest) Reset() {
	*x = CreateRoundRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_round_message_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateRoundRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRoundRequest) ProtoMessage() {}

func (x *CreateRoundRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_round_message_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRoundRequest.ProtoReflect.Descriptor instead.
func (*CreateRoundRequest) Descriptor() ([]byte, []int) {
	return file_protos_round_message_proto_rawDescGZIP(), []int{5}
}

func (x *CreateRoundRequest) GetItem() *RoundMessage {
	if x != nil {
		return x.Item
	}
	return nil
}

type CreateRoundResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Item *RoundMessage `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
}

func (x *CreateRoundResponse) Reset() {
	*x = CreateRoundResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_round_message_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateRoundResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRoundResponse) ProtoMessage() {}

func (x *CreateRoundResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_round_message_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRoundResponse.ProtoReflect.Descriptor instead.
func (*CreateRoundResponse) Descriptor() ([]byte, []int) {
	return file_protos_round_message_proto_rawDescGZIP(), []int{6}
}

func (x *CreateRoundResponse) GetItem() *RoundMessage {
	if x != nil {
		return x.Item
	}
	return nil
}

type UpdateRoundRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   string        `protobuf:"bytes,1,opt,name=Id,json=id,proto3" json:"Id,omitempty"`
	Item *RoundMessage `protobuf:"bytes,2,opt,name=item,proto3" json:"item,omitempty"`
}

func (x *UpdateRoundRequest) Reset() {
	*x = UpdateRoundRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_round_message_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateRoundRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRoundRequest) ProtoMessage() {}

func (x *UpdateRoundRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_round_message_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRoundRequest.ProtoReflect.Descriptor instead.
func (*UpdateRoundRequest) Descriptor() ([]byte, []int) {
	return file_protos_round_message_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateRoundRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateRoundRequest) GetItem() *RoundMessage {
	if x != nil {
		return x.Item
	}
	return nil
}

type UpdateRoundResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Item *RoundMessage `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
}

func (x *UpdateRoundResponse) Reset() {
	*x = UpdateRoundResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_round_message_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateRoundResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRoundResponse) ProtoMessage() {}

func (x *UpdateRoundResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_round_message_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRoundResponse.ProtoReflect.Descriptor instead.
func (*UpdateRoundResponse) Descriptor() ([]byte, []int) {
	return file_protos_round_message_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateRoundResponse) GetItem() *RoundMessage {
	if x != nil {
		return x.Item
	}
	return nil
}

type DeleteRoundRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=Id,json=id,proto3" json:"Id,omitempty"`
}

func (x *DeleteRoundRequest) Reset() {
	*x = DeleteRoundRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_round_message_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteRoundRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRoundRequest) ProtoMessage() {}

func (x *DeleteRoundRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_round_message_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRoundRequest.ProtoReflect.Descriptor instead.
func (*DeleteRoundRequest) Descriptor() ([]byte, []int) {
	return file_protos_round_message_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteRoundRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteRoundResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteRoundResponse) Reset() {
	*x = DeleteRoundResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_round_message_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteRoundResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRoundResponse) ProtoMessage() {}

func (x *DeleteRoundResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_round_message_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRoundResponse.ProtoReflect.Descriptor instead.
func (*DeleteRoundResponse) Descriptor() ([]byte, []int) {
	return file_protos_round_message_proto_rawDescGZIP(), []int{10}
}

var File_protos_round_message_proto protoreflect.FileDescriptor

var file_protos_round_message_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x2f, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x72, 0x6f,
	0x75, 0x6e, 0x64, 0x22, 0x48, 0x0a, 0x0c, 0x52, 0x6f, 0x75, 0x6e, 0x64, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x53, 0x63, 0x6f, 0x72, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x02, 0x52, 0x05, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x22, 0x12, 0x0a,
	0x10, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x6f, 0x75, 0x6e, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x22, 0x3e, 0x0a, 0x11, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x6f, 0x75, 0x6e, 0x64, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x29, 0x0a, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x2e, 0x52, 0x6f,
	0x75, 0x6e, 0x64, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x05, 0x69, 0x74, 0x65, 0x6d,
	0x73, 0x22, 0x21, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x52, 0x6f, 0x75, 0x6e, 0x64, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x02, 0x69, 0x64, 0x22, 0x3b, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x52, 0x6f, 0x75, 0x6e, 0x64,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x27, 0x0a, 0x04, 0x69, 0x74, 0x65, 0x6d,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x2e, 0x52,
	0x6f, 0x75, 0x6e, 0x64, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x04, 0x69, 0x74, 0x65,
	0x6d, 0x22, 0x3d, 0x0a, 0x12, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x6f, 0x75, 0x6e, 0x64,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x27, 0x0a, 0x04, 0x69, 0x74, 0x65, 0x6d, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x2e, 0x52, 0x6f,
	0x75, 0x6e, 0x64, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x04, 0x69, 0x74, 0x65, 0x6d,
	0x22, 0x3e, 0x0a, 0x13, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x6f, 0x75, 0x6e, 0x64, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x27, 0x0a, 0x04, 0x69, 0x74, 0x65, 0x6d, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x2e, 0x52, 0x6f,
	0x75, 0x6e, 0x64, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x04, 0x69, 0x74, 0x65, 0x6d,
	0x22, 0x4d, 0x0a, 0x12, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x6f, 0x75, 0x6e, 0x64, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x27, 0x0a, 0x04, 0x69, 0x74, 0x65, 0x6d, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x2e, 0x52, 0x6f, 0x75,
	0x6e, 0x64, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x04, 0x69, 0x74, 0x65, 0x6d, 0x22,
	0x3e, 0x0a, 0x13, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x6f, 0x75, 0x6e, 0x64, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x27, 0x0a, 0x04, 0x69, 0x74, 0x65, 0x6d, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x2e, 0x52, 0x6f, 0x75,
	0x6e, 0x64, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x04, 0x69, 0x74, 0x65, 0x6d, 0x22,
	0x24, 0x0a, 0x12, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x6f, 0x75, 0x6e, 0x64, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x15, 0x0a, 0x13, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52,
	0x6f, 0x75, 0x6e, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x07, 0x5a, 0x05,
	0x72, 0x6f, 0x75, 0x6e, 0x64, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protos_round_message_proto_rawDescOnce sync.Once
	file_protos_round_message_proto_rawDescData = file_protos_round_message_proto_rawDesc
)

func file_protos_round_message_proto_rawDescGZIP() []byte {
	file_protos_round_message_proto_rawDescOnce.Do(func() {
		file_protos_round_message_proto_rawDescData = protoimpl.X.CompressGZIP(file_protos_round_message_proto_rawDescData)
	})
	return file_protos_round_message_proto_rawDescData
}

var file_protos_round_message_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_protos_round_message_proto_goTypes = []interface{}{
	(*RoundMessage)(nil),        // 0: round.RoundMessage
	(*ListRoundRequest)(nil),    // 1: round.ListRoundRequest
	(*ListRoundResponse)(nil),   // 2: round.ListRoundResponse
	(*GetRoundRequest)(nil),     // 3: round.GetRoundRequest
	(*GetRoundResponse)(nil),    // 4: round.GetRoundResponse
	(*CreateRoundRequest)(nil),  // 5: round.CreateRoundRequest
	(*CreateRoundResponse)(nil), // 6: round.CreateRoundResponse
	(*UpdateRoundRequest)(nil),  // 7: round.UpdateRoundRequest
	(*UpdateRoundResponse)(nil), // 8: round.UpdateRoundResponse
	(*DeleteRoundRequest)(nil),  // 9: round.DeleteRoundRequest
	(*DeleteRoundResponse)(nil), // 10: round.DeleteRoundResponse
}
var file_protos_round_message_proto_depIdxs = []int32{
	0, // 0: round.ListRoundResponse.items:type_name -> round.RoundMessage
	0, // 1: round.GetRoundResponse.item:type_name -> round.RoundMessage
	0, // 2: round.CreateRoundRequest.item:type_name -> round.RoundMessage
	0, // 3: round.CreateRoundResponse.item:type_name -> round.RoundMessage
	0, // 4: round.UpdateRoundRequest.item:type_name -> round.RoundMessage
	0, // 5: round.UpdateRoundResponse.item:type_name -> round.RoundMessage
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_protos_round_message_proto_init() }
func file_protos_round_message_proto_init() {
	if File_protos_round_message_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protos_round_message_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RoundMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_round_message_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListRoundRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_round_message_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListRoundResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_round_message_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetRoundRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_round_message_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetRoundResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_round_message_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateRoundRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_round_message_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateRoundResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_round_message_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateRoundRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_round_message_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateRoundResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_round_message_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteRoundRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_round_message_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteRoundResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protos_round_message_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protos_round_message_proto_goTypes,
		DependencyIndexes: file_protos_round_message_proto_depIdxs,
		MessageInfos:      file_protos_round_message_proto_msgTypes,
	}.Build()
	File_protos_round_message_proto = out.File
	file_protos_round_message_proto_rawDesc = nil
	file_protos_round_message_proto_goTypes = nil
	file_protos_round_message_proto_depIdxs = nil
}
